export const questions = [
	{
		id: "Poste",
		text: "Positionnement enquêteur (possibilité de se déplacer)",
		options: [
			{ id: "1", text: "Quais -> Préciser le numéro du quai", next: "Quai" },
			{ id: "2", text: "Parvis Est (entrée principale)", next: "Sens" },
			{ id: "3", text: "Parvis Est (entrée BV)", next: "Sens" },
			{ id: "4", text: "Parvis Ouest (PASO)", next: "Sens" },
			{ id: "5", text: "Parvis Ouest (passerelle)", next: "Sens" },
		],
	},
	{
		id: "Quai",
		text: "Precisez le Quai",
		freeText: true,
		next: "Sens",
	},
	{
		id: "Sens",
		text: "Sens",
		options: [
			{ id: "1", text: "entre en gare (si l'enquêteur est situé sur le quai et que les interviewés vont prendre le train, considérer que l'interviewé entre en gare)", next: "TempO" },
			{ id: "2", text: "sort de la gare (si l'enquêteur est situé sur le quai et que les interviewés sortent du train, considérer que l'interviewé sort de la gare)", next: "TempD" },
		],
	},
	{
		id: "TempO",
		text: "Combien de temps avez-vous mis pour arriver à la gare où nous nous trouvons actuellement ?",
		freeText: true,
		next: "DepO",
	},
	{
		id: "TempD",
		text: "Combien de temps allez-vous mettre depuis la gare de Corbeil Essonnes pour arriver à destination ?",
		freeText: true,
		next: "DepO",
	},
	{
		id: "DepO",
		text: "Commune d'Origine",
		usesCommuneSelector: true,
		next: "MotifO",
	},
	{
		id: "MotifO",
		text: "Ce lieu est-il...?",
		options: [
			{ id: "1", text: "Votre domicile", next: "DepD" },
			{ id: "2", text: "Votre lieu de travail habituel", next: "DepD" },
			{ id: "3", text: "Un lieu de rendez-vous professionnel", next: "DepD" },
			{ id: "4", text: "Votre établissement scolaire, université", next: "DepD" },
			{ id: "5", text: "Un lieu d'achats, courses...", next: "DepD" },
			{ id: "6", text: "Un lieu de loisirs / tourisme / hôtel", next: "DepD" },
			{ id: "7", text: "Autre, précisez :", next: "MotifAutre", requiresPrecision: true },
		],
	},
	{
		id: "MotifAutre",
		text: "Precisez :",
		freeText: true,
		next: "DepD",
	},
	{
		id: "DepD",
		text: "Commune de Destination",
		usesCommuneSelector: true,
		next: "MotifD",
	},
	{
		id: "MotifD",
		text: "Ce lieu est-il...?",
		options: [
			{ id: "1", text: "Votre domicile", next: "Freq" },
			{ id: "2", text: "Votre lieu de travail habituel", next: "Freq" },
			{ id: "3", text: "Un lieu de rendez-vous professionnel", next: "Freq" },
			{ id: "4", text: "Votre établissement scolaire, université", next: "Freq" },
			{ id: "5", text: "Un lieu d'achats, courses...", next: "Freq" },
			{ id: "6", text: "Un lieu de loisirs / tourisme / hôtel", next: "Freq" },
			{ id: "7", text: "Autre, précisez :", next: "MotifD_Autre", requiresPrecision: true },
		],
	},
	{
		id: "MotifD_Autre",
		text: "Precisez :",
		freeText: true,
		next: "Freq",
	},
	{
		id: "Freq",
		text: "À quelle fréquence vous rendez-vous à la gare de Corbeil Essonnes ?",
		options: [
			{ id: "1", text: "Tous les jours (7/7)", next: "ModeO" },
			{ id: "2", text: "Régulièrement (5-6 fois par semaine)", next: "ModeO" },
			{ id: "3", text: "Souvent (3-4 fois par semaine)", next: "ModeO" },
			{ id: "4", text: "De temps en temps (1-2 fois par semaine)", next: "ModeO" },
			{ id: "5", text: "Occasionnellement (moins d'1 fois par semaine)", next: "ModeO" },
			{ id: "6", text: "Rarement (1 fois à quelquefois par an)", next: "ModeO" },
		],
	},
	{
		id: "ModeO",
		text: "Par quel mode de transport êtes-vous venu à la gare ou nous nous trouvons actuellement ?",
		options: [
			{ id: "1", text: "En voiture conducteur seul, stationné près de la gare", next: "Localisation_14a_ModeO" },
			{ id: "2", text: "En voiture covoiturage (passager ou conducteur), stationné près de la gare", next: "Localisation_14a_ModeO" },
			{ id: "3", text: "En voiture, déposé (pas de stationnement)", next: "Localisation_15_ModeO" },
			{ id: "4", text: "En taxi", next: "Localisation_15_ModeO" },
			{ id: "5", text: "En VTC", next: "Localisation_15_ModeO" },
			{ id: "6", text: "En deux-roues motorisées", next: "Localisation_14a_ModeO" },
			{ id: "7", text: "En bus/car - gare routière Emile Zola (côté Ouest cimetière)", next: "19d_O" },
			{ id: "8", text: "En bus/car - gare routière place Henri Barbusse (côté Est centre-ville)", next: "19e_O" },
			{ id: "9", text: "En RER", next: "ModeD" },
			{ id: "10", text: "En vélo", next: "18a_O" },
			{ id: "11", text: "À pied exclusivement", next: "ModeD" },
			{ id: "12", text: "Autre précisez", next: "ModeO_Autre", requiresPrecision: true },
		],
	},
	{
		id: "ModeO_Autre",
		text: "Precisez :",
		freeText: true,
		next: "ModeD",
	},
	{
		id: "Localisation_14a_ModeO",
		text: "Où êtes-vous garé ?",
		options: [
			{ id: "1", text: "Parking barriéré gare (pont chaud)", next: "TempsStationnementO" },
			{ id: "2", text: "Parking de l'hôtel de la Gare", next: "TempsStationnementO" },
			{ id: "3", text: "Parking Seine", next: "TempsStationnementO" },
			{ id: "4", text: "Sur voirie, préciser le nom de la rue si possible + voir plan", next: "Localisation_14a_ModeO_Autre", requiresPrecision: true },
			{ id: "5", text: "Autre parking, préciser...", next: "Localisation_14a_ModeO_Autre", requiresPrecision: true },
		],
	},
	{
		id: "Localisation_14a_ModeO_Autre",
		text: "Precisez :",
		freeText: true,
		next: "TempsStationnementO",
	},
	{
		id: "TempsStationnementO",
		text: "Combien de temps allez-vous rester stationné ?",
		options: [
			{ id: "1", text: "Moins de 2 heures", next: "ModeD" },
			{ id: "2", text: "Une demi-journée (entre 2 et 4 heures)", next: "ModeD" },
			{ id: "3", text: "Une journée entière (entre 4h et 12h)", next: "ModeD" },
			{ id: "4", text: "2 à 3 jours", next: "ModeD" },
			{ id: "5", text: "3 à 6 jours", next: "ModeD" },
			{ id: "6", text: "1 semaine ou plus", next: "ModeD" },
		],
	},
	{
		id: "Localisation_15_ModeO",
		text: "Où se passe la dépose/reprise ?",
		options: [
			{ id: "1", text: "Dans le parking taxis", next: "ModeD" },
			{ id: "2", text: "Dans la gare routière place Henri Barbusse côté Est/Centre-ville", next: "ModeD" },
			{ id: "3", text: "Dans la gare routière Emile Zola côté Ouest/Cimetière", next: "ModeD" },
			{ id: "4", text: "Dans le Parking barriéré gare (pont chaud)", next: "ModeD" },
			{ id: "5", text: "Sur voirie - Av. Darblay", next: "ModeD" },
			{ id: "6", text: "Sur voirie - Rue de Seine", next: "ModeD" },
			{ id: "7", text: "Sur voirie - Rue Félicien Rops", next: "ModeD" },
			{ id: "8", text: "Sur voirie - Rue Emile Zola", next: "ModeD" },
			{ id: "9", text: "Sur voirie - autre", next: "Localisation_15_ModeO_Autre", requiresPrecision: true },
			{ id: "10", text: "Parking de l'hôtel de la Gare", next: "ModeD" },
			{ id: "11", text: "Parking Seine", next: "ModeD" },
			{ id: "12", text: "Autre parking, préciser...", next: "Localisation_15_ModeO_Autre", requiresPrecision: true },
		],
	},
	{
		id: "Localisation_15_ModeO_Autre",
		text: "Precisez :",
		freeText: true,
		next: "ModeD",
	},
	{
		id: "18a_O",
		text: "Où êtes vous stationné ?",
		options: [
			{ id: "1", text: "Côté Est/Centre-Ville - Arceaux gare routière", next: "18b_O" },
			{ id: "2", text: "Côté Est/Centre-Ville - Consigne sécurisée vélo", next: "18b_O" },
			{ id: "3", text: "Côté Ouest/Cimetière - Arceaux", next: "18b_O" },
			{ id: "4", text: "Vélo embarqué dans le train", next: "18b_O" },
			{ id: "5", text: "Sur voirie hors arceaux", next: "18b_O" },
		],
	},
	{
		id: "18b_O",
		text: "Êtes-vous satisfait de l'offre de stationnement cyclable et des aménagements cyclables ?",
		options: [
			{ id: "1", text: "Oui", next: "ModeD" },
			{ id: "2", text: "Non", next: "18c_O" },
		],
	},
	{
		id: "18c_O",
		text: "Si non, Expliquer pourquoi",
		options: [
			{ id: "1", text: "Nombre de stationnements vélo insuffisant", next: "ModeD" },
			{ id: "2", text: "Offre de stationnement mal positionnée", next: "ModeD" },
			{ id: "3", text: "Aménagement cyclables insuffisants", next: "ModeD" },
			{ id: "4", text: "Autres, à préciser", next: "18c_O_Autre", requiresPrecision: true },
		],
		multipleChoice: true,
	},
	{
		id: "18c_O_Autre",
		text: "Precisez :",
		freeText: true,
		next: "ModeD",
	},
	{
		id: "19d_O",
		text: "Comment trouvez-vous la gare routière Emile Zola (côté Ouest/Cimetière)?",
		options: [
			{ id: "1", text: "bien dimensionnée", next: "ModeD" },
			{ id: "2", text: "fonctionnelle", next: "ModeD" },
			{ id: "3", text: "propre", next: "ModeD" },
			{ id: "4", text: "agréable", next: "ModeD" },
			{ id: "5", text: "sécurisée", next: "ModeD" },
			{ id: "6", text: "Bien indiquée", next: "ModeD" },
			{ id: "7", text: "suffisamment éclairée", next: "ModeD" },
			{ id: "8", text: "Autre, préciser", next: "19dO_Autre", requiresPrecision: true },
		],
		multipleChoice: true,
	},
	{
		id: "19dO_Autre",
		text: "Precisez :",
		freeText: true,
		next: "ModeD",
	},
	{
		id: "19e_O",
		text: "Comment trouvez-vous la gare routière place Henri Barbusse (côté Est/centre-ville)?",
		options: [
			{ id: "1", text: "bien dimensionnée", next: "ModeD" },
			{ id: "2", text: "fonctionnelle", next: "ModeD" },
			{ id: "3", text: "propre", next: "ModeD" },
			{ id: "4", text: "agréable", next: "ModeD" },
			{ id: "5", text: "sécurisée", next: "ModeD" },
			{ id: "6", text: "Bien indiquée", next: "ModeD" },
			{ id: "7", text: "suffisamment éclairée", next: "ModeD" },
			{ id: "8", text: "Autre, préciser", next: "19e_O_Autre", requiresPrecision: true },
		],
		multipleChoice: true,
	},
	{
		id: "19e_O_Autre",
		text: "Precisez :",
		freeText: true,
		next: "ModeD",
	},
	
	{
		id: "ModeD",
		text: "Quel mode allez-vous utiliser ensuite pour vous rendre à votre destination ?",
		options: [
			{ id: "1", text: "En voiture conducteur seul, stationné près de la gare", next: "Localisation_14a_ModeD" },
			{ id: "2", text: "En voiture covoiturage (passager ou conducteur), stationné près de la gare", next: "Localisation_14a_ModeD" },
			{ id: "3", text: "En voiture, déposé (pas de stationnement)", next: "Localisation_15_ModeD" },
			{ id: "4", text: "En taxi", next: "Localisation_15_ModeD" },
			{ id: "5", text: "En VTC", next: "Localisation_15_ModeD" },
			{ id: "6", text: "En deux-roues motorisées", next: "Localisation_14a_ModeD" },
			{ id: "7", text: "En bus/car - gare routière Emile Zola (côté Ouest cimetière)", next: "19d_D" },
			{ id: "8", text: "En bus/car - gare routière place Henri Barbusse (côté Est centre-ville)", next: "19e_D" },
			{ id: "9", text: "En RER", next: "Q10" },
			{ id: "10", text: "En vélo", next: "18a_D" },
			{ id: "11", text: "À pied exclusivement", next: "Q10" },
			{ id: "12", text: "Autre précisez", next: "ModeD_Autre", requiresPrecision: true },
		],
	},
	{
		id: "ModeD_Autre",
		text: "Precisez :",
		freeText: true,
		next: "Q10",
	},
	{
		id: "Localisation_14a_ModeD",
		text: "Où êtes-vous garé ?",
		options: [
			{ id: "1", text: "Parking barriéré gare (pont chaud)", next: "TempsStationnementD" },
			{ id: "2", text: "Parking de l'hôtel de la Gare", next: "TempsStationnementD" },
			{ id: "3", text: "Parking Seine", next: "TempsStationnementD" },
			{ id: "4", text: "Sur voirie, préciser le nom de la rue si possible + voir plan", next: "Localisation_14a_ModeD_Autre", requiresPrecision: true },
			{ id: "5", text: "Autre parking, préciser...", next: "Localisation_14a_ModeD_Autre", requiresPrecision: true },
		],
	},
	{
		id: "Localisation_14a_ModeD_Autre",
		text: "Precisez :",
		freeText: true,
		next: "TempsStationnementD",
	},
	{
		id: "TempsStationnementD",
		text: "Combien de temps allez-vous rester stationné ?",
		options: [
			{ id: "1", text: "Moins de 2 heures", next: "Q10" },
			{ id: "2", text: "Une demi-journée (entre 2 et 4 heures)", next: "Q10" },
			{ id: "3", text: "Une journée entière (entre 4h et 12h)", next: "Q10" },
			{ id: "4", text: "2 à 3 jours", next: "Q10" },
			{ id: "5", text: "3 à 6 jours", next: "Q10" },
			{ id: "6", text: "1 semaine ou plus", next: "Q10" },
		],
	},
	{
		id: "Localisation_15_ModeD",
		text: "Où se passe la dépose/reprise ?",
		options: [
			{ id: "1", text: "Dans le parking taxis", next: "Q10" },
			{ id: "2", text: "Dans la gare routière place Henri Barbusse côté Est/Centre-ville", next: "Q10" },
			{ id: "3", text: "Dans la gare routière Emile Zola côté Ouest/Cimetière", next: "Q10" },
			{ id: "4", text: "Dans le Parking barriéré gare (pont chaud)", next: "Q10" },
			{ id: "5", text: "Sur voirie - Av. Darblay", next: "Q10" },
			{ id: "6", text: "Sur voirie - Rue de Seine", next: "Q10" },
			{ id: "7", text: "Sur voirie - Rue Félicien Rops", next: "Q10" },
			{ id: "8", text: "Sur voirie - Rue Emile Zola", next: "Q10" },
			{ id: "9", text: "Sur voirie - autre", next: "Localisation_15_ModeD_Autre", requiresPrecision: true },
			{ id: "10", text: "Parking de l'hôtel de la Gare", next: "Q10" },
			{ id: "11", text: "Parking Seine", next: "Q10" },
			{ id: "12", text: "Autre parking, préciser...", next: "Localisation_15_ModeD_Autre", requiresPrecision: true },
		],
	},
	{
		id: "Localisation_15_ModeD_Autre",
		text: "Precisez :",
		freeText: true,
		next: "Q10",
	},
	{
		id: "18a_D",
		text: "Où êtes vous stationné ?",
		options: [
			{ id: "1", text: "Côté Est/Centre-Ville - Arceaux gare routière", next: "18b_D" },
			{ id: "2", text: "Côté Est/Centre-Ville - Consigne sécurisée vélo", next: "18b_D" },
			{ id: "3", text: "Côté Ouest/Cimetière - Arceaux", next: "18b_D" },
			{ id: "4", text: "Vélo embarqué dans le train", next: "18b_D" },
			{ id: "5", text: "Sur voirie hors arceaux", next: "18b_D" },
		],
	},
	{
		id: "18b_D",
		text: "Êtes-vous satisfait de l'offre de stationnement cyclable et des aménagements cyclables ?",
		options: [
			{ id: "1", text: "Oui", next: "Q10" },
			{ id: "2", text: "Non", next: "18c_D" },
		],
	},
	{
		id: "18c_D",
		text: "Si non, Expliquer pourquoi",
		options: [
			{ id: "1", text: "Nombre de stationnements vélo insuffisant", next: "Q10" },
			{ id: "2", text: "Offre de stationnement mal positionnée", next: "Q10" },
			{ id: "3", text: "Aménagement cyclables insuffisants", next: "Q10" },
			{ id: "4", text: "Autres, à préciser", next: "18c_D_Autre", requiresPrecision: true },
		],
		multipleChoice: true,
	},
	{
		id: "18c_D_Autre",
		text: "Precisez :",
		freeText: true,
		next: "Q10",
	},
	{
		id: "19d_D",
		text: "Comment trouvez-vous la gare routière Emile Zola (côté Ouest/Cimetière)?",
		options: [
			{ id: "1", text: "bien dimensionnée", next: "Q10" },
			{ id: "2", text: "fonctionnelle", next: "Q10" },
			{ id: "3", text: "propre", next: "Q10" },
			{ id: "4", text: "agréable", next: "Q10" },
			{ id: "5", text: "sécurisée", next: "Q10" },
			{ id: "6", text: "Bien indiquée", next: "Q10" },
			{ id: "7", text: "suffisamment éclairée", next: "Q10" },
			{ id: "8", text: "Autre, préciser", next: "19d_D_Autre", requiresPrecision: true },
		],
		multipleChoice: true,
	},
	{
		id: "19d_D_Autre",
		text: "Precisez :",
		freeText: true,
		next: "Q10",
	},
	{
		id: "19e_D",
		text: "Comment trouvez-vous la gare routière place Henri Barbusse (côté Est/centre-ville)?",
		options: [
			{ id: "1", text: "bien dimensionnée", next: "Q10" },
			{ id: "2", text: "fonctionnelle", next: "Q10" },
			{ id: "3", text: "propre", next: "Q10" },
			{ id: "4", text: "agréable", next: "Q10" },
			{ id: "5", text: "sécurisée", next: "Q10" },
			{ id: "6", text: "Bien indiquée", next: "Q10" },
			{ id: "7", text: "suffisamment éclairée", next: "Q10" },
			{ id: "8", text: "Autre, préciser", next: "19e_D_Autre", requiresPrecision: true },
		],
		multipleChoice: true,
	},
	{
		id: "19e_D_Autre",
		text: "Precisez :",
		freeText: true,
		next: "Q10",
	},
	{
		id: "Q10",
		text: "Quel accès gare avez-vous ou allez-vous utiliser ?",
		options: [
			{ id: "1", text: "PASO côté Ouest/Cimetière", next: "Q12" },
			{ id: "2", text: "PASO côté Est/ Centre-ville", next: "Q12" },
			{ id: "3", text: "Passerelle côté Ouest/cimetière", next: "Q12" },
			{ id: "4", text: "Passerelle côté Est/Centre-ville", next: "Q12" },
			{ id: "5", text: "Côté Est/Centre-ville - Accès direct au quai", next: "Q12" },
		],
	},

	{
		id: "Q12",
		text: "Est-ce qu'il vous arrive de traverser la gare (sans prendre le RER ni prendre le bus) pour rejoindre des quartiers de Corbeil-Essonnes?",
		options: [
			{ id: "1", text: "Oui", next: "Q13" },
			{ id: "2", text: "Non", next: "non_utilisation_bus" },
		],
	},
	{
		id: "Q13",
		text: "Si oui, à quelle fréquence ?",
		options: [
			{ id: "1", text: "tous les jours (7/7)", next: "non_utilisation_bus" },
			{ id: "2", text: "régulièrement (5-6 fois par semaine)", next: "non_utilisation_bus" },
			{ id: "3", text: "souvent (3-4 fois par semaine)", next: "non_utilisation_bus" },
			{ id: "4", text: "de temps en temps (1-2 fois par semaine)", next: "non_utilisation_bus" },
			{ id: "5", text: "occasionnellement (moins d'1 fois par semaine)", next: "non_utilisation_bus" },
			{ id: "6", text: "rarement (1 fois à quelquefois par an)", next: "non_utilisation_bus" },
		],
	},

	{
		id: "non_utilisation_bus",
		text: "Pourquoi n'utilisez-vous pas le bus ? (réponse pouvant être multiple)",
		options: [
			{ id: "1", text: "Je suis venu/je repars en bus", next: "non_utilisation_velo" },
			{ id: "2", text: "pas de desserte bus", next: "non_utilisation_velo" },
			{ id: "3", text: "temps de trajet trop long", next: "non_utilisation_velo" },
			{ id: "4", text: "horaires inadaptés", next: "non_utilisation_velo" },
			{ id: "5", text: "bus inconfortables", next: "non_utilisation_velo" },
			{ id: "6", text: "préférence pour la voiture", next: "non_utilisation_velo" },
			{ id: "7", text: "n'y a pas pensé", next: "non_utilisation_velo" },
			{ id: "8", text: "insécurité", next: "non_utilisation_velo" },
			{ id: "9", text: "autres, précisez…", next: "non_utilisation_bus_Autre", requiresPrecision: true },
		],
		multipleChoice: true,
	},
	{
		id: "non_utilisation_bus_Autre",
		text: "Precisez :",
		freeText: true,
		next: "non_utilisation_velo",
	},
	{
		id: "non_utilisation_velo",
		text: "Pourquoi n'utilisez-vous pas le vélo ?",
		options: [
			{ id: "1", text: "j'utilise le vélo", next: "20" },
			{ id: "2", text: "pas de vélo", next: "20" },
			{ id: "3", text: "distance trop longue", next: "20" },
			{ id: "4", text: "pas de stationnement sécurisé", next: "20" },
			{ id: "5", text: "itinéraire dangereux", next: "20" },
			{ id: "6", text: "n'y a pas pensé", next: "20" },
			{ id: "7", text: "pas de  piste cyclable", next: "20" },
			{ id: "8", text: "Autres, précisez...", next: "non_utilisation_velo_Autre", requiresPrecision: true },
		],
		multipleChoice: true,
	},
	{
		id: "non_utilisation_velo_Autre",
		text: "Precisez :",
		freeText: true,
		next: "20",
	},
	{
		id: "20",
		text: "Si un parking relais est construit à 5 min à pied de la gare, seriez-vous intéressé pour l'utiliser ?",
		options: [
			{ id: "1", text: "Oui, si c'est gratuit", next: "21" },
			{ id: "2", text: "Oui, si des tarifs préférentiels sont proposés", next: "21" },
			{ id: "3", text: "Non, je préfère me garer au plus proche de la gare", next: "21" },
			{ id: "4", text: "Non, je préfère me garer gratuitement", next: "21" },
			{ id: "5", text: "Non, autre raison", next: "21", requiresPrecision: true },
		],
		multipleChoice: true,
	},
	{
		id: "21",
		text: "Selon vous, qu'est ce qui devrait être amélioré au niveau de la gare de Corbeil Essonnes ?",
		options: [
			{ id: "1", text: "Parvis de gare", next: "end" },
			{ id: "2", text: "Gare routière Emile Zola (côté Ouest cimetière)", next: "end" },
			{ id: "3", text: "Gare routière Henri Barbusse (côté Est Centre-ville)", next: "end" },
			{ id: "4", text: "Information et repérage en gare", next: "end" },
			{ id: "5", text: "Stationnement", next: "end" },
			{ id: "6", text: "Sécurité", next: "end" },
			{ id: "7", text: "Confort", next: "end" },
			{ id: "8", text: "Service en gare", next: "end" },
			{ id: "9", text: "Dépose-minute", next: "end" },
			{ id: "10", text: "Aménagement des voies", next: "end" },
			{ id: "11", text: "Autre", next: "end", requiresPrecision: true },
		],
		multipleChoice: true,
	},
];